export interface CountryProperties {
    scalerank: number;
    featurecla: string;
    labelrank: number;
    sovereignt: string;
    sov_a3: string | number;
    adm0_dif: number;
    level: number;
    type: string;
    admin: string;
    adm0_a3: string | number;
    geou_dif: number;
    geounit: string;
    gu_a3: string | number;
    su_dif: number;
    subunit: string;
    su_a3: string;
    brk_diff: number;
    name: string;
    name_long: string;
    brk_a3: string | number;
    brk_name: string;
    brk_group: string;
    abbrev: string;
    postal: string;
    formal_en: string;
    formal_fr: string;
    note_adm0: string;
    note_brk: string;
    name_sort: string;
    name_alt: string;
    mapcolor7: number;
    mapcolor8: number;
    mapcolor9: number;
    mapcolor13: number;
    pop_est: number;
    gdp_md_est: number;
    pop_year: number;
    lastcensus: number;
    gdp_year: number;
    economy: string;
    income_grp: string;
    wikipedia: number;
    fips_10: string;
    iso_a2: string;
    iso_a3: string | number;
    iso_n3: number;
    un_a3: number;
    wb_a2: string;
    wb_a3: string;
    woe_id: number;
    adm0_a3_is: string;
    adm0_a3_us: string;
    adm0_a3_un: number;
    adm0_a3_wb: number;
    continent: string;
    region_un: string;
    subregion: string;
    region_wb: string;
    name_len: number;
    long_len: number;
    abbrev_len: number;
    tiny: number;
    homepart: number;
    region: string;
}
