name: run_and_deploy_model
on:
   push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 0 1/1 * ? *'
jobs:
  update_model:
    runs-on: ubuntu-latest
    steps:
      - name: 'Update model'
        env:
          PASSWORD:1234
        run:
          docker run stuartlynn/africa-covid-model:1.0 Rscript ModelPipeline.R
