name: run_and_deploy_model
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'
jobs:
  update_model:
    runs-on: ubuntu-latest
    steps:
      - name: 'Update model'
        run:
          docker run stuartlynn/africa-covid-model:1.2.7 Rscript ModelPipeline.R
